#git pipelines觸發
trigger:
- 'none'

#定義變數群組
variables:
  - group: Azure Registry Login

#腳本執行進入點
stages:
- stage: AzureWebAppServiceBuild
  displayName: "AzureWebAppServiceBuild"
  jobs:
  - job: PythonImageBuild
    displayName: "PythonImageBuild"
    steps:   
    #DockerCompose
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(1)(eb76b2aa-fd5d-4aed-a836-a830c995d714)'
        azureContainerRegistry: '{"loginServer":"godprojectregistry.azurecr.io", "id" : "/subscriptions/eb76b2aa-fd5d-4aed-a836-a830c995d714/resourceGroups/myPythonServer/providers/Microsoft.ContainerRegistry/registries/GodProjectRegistry"}'
        dockerComposeFile: 'python/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: '--env-file python/.env up -d --build'
    #DockerImages
    - script: |
             docker images
      displayName: 'AZURE DOCKER IMAGE LIST'
    #DockerBuildAndPush
    - script: |
             docker login $(REGISTRY_HOST) -u $(REGISTRY_USER) -p $(REGISTRY_PASSWORD)
             docker tag mypythonweb:1.0 $(REGISTRY_IMAGE)
             docker push $(REGISTRY_IMAGE)
      displayName: 'AZURE DOCKER REGISTRY LOGIN AND PUSH IMAGE'
    #AzureWebAppContainer
    - task: AzureWebAppContainer@1
      displayName: 'AZURE WEB APP SERVICE BUILD'
      inputs:
        azureSubscription: 'Azure for Students(eb76b2aa-fd5d-4aed-a836-a830c995d714)'
        appName: 'myPythonServer'
        containers: '$(REGISTRY_IMAGE)'
    #CALL STORE PROCEDURE TO CREATE DB AND INSERT DATA
    - task: ShellScript@2
      displayName: 'CALL SP TO CREATE DB AND INSERT DATA'
      inputs:
        scriptPath: 'AutoSPImport.sh'